name: SeleneChat
version: 0.1.0-SNAPSHOT
description: Chat plugin inspired by LunaChat
main: io.github.bluesheep2804.selenechat.SeleneChatSpigot
author: BlueSheep2804
api-version: 1.16

commands:
  message:
    description: Selenechat message command
    aliases:
      - msg
      - tell
      - w
    permission: selenechat.command.message

permissions:
  selenechat.command.message:
    description: Allow using SeleneChat message command
    default: true